# Guia de Matemática Basica Aplicada

## Importação dos Pacotes
<p>Bibliotecas que serão utilizadas durante os códigos.</p>

In [1]:
# Pacote que contem funções básicas para calculos estatísticos de tendencia central e variações.
using Statistics
# Pacote que contem funções para calculos de Algebra Linear.
using LinearAlgebra

## Estatística
<p>Funções que evidenciam informações intrísecas dos dados.</p>

In [2]:
# Vetores com alguns dados para serem usados nos exemplos.
dados = [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 3, 1, 5, 2, 3, 4, 5];
rel = [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9];

In [3]:
# Função que retorna o tamanho do vetor.
length(dados)

18

In [4]:
# Função que calcula o Desvio Padrão (Standard Deviation) do vetor.
std(dados)

1.495090003192804

In [5]:
# Função que calcula a Variância do vetor.
var(dados)

2.235294117647059

In [6]:
# Função que calcula a Correlação de Pearson.
# Quanto mais proximo de zero, menor a correlação. 
# Quanto mais proximo de um, maior a correlação
cor(dados, rel)

0.29617443887954614

In [7]:
# Função que calcula a média do vetor.
mean(dados)

3.0

In [8]:
# Função que retorna a mediana do vetor.
median(dados)

3.0

In [9]:
# Função que calcula a média entre dois valores escalares.
middle(3, 2)

2.5

## Algebra Linear
<p>Funções que trabalham com dados em formato de matrizes e vetores.</p>

In [10]:
# Vetor Coluna.
coluna = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [11]:
# Vetor Linha.
linha = [1 2 3]

1×3 Array{Int64,2}:
 1  2  3

In [12]:
# Matriz, é como uma junção do vetor linha x coluna porem com ponto-virgula.
matriz = [1 2; 1 3]
mul = [2 3; 4 5]

2×2 Array{Int64,2}:
 2  3
 4  5

In [13]:
# Função que retorna uma matriz de zeros com a ordem (linha, coluna).
zeros(3, 3)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [14]:
# Função que retorna uma matriz de zeros com a ordem (linha, coluna).
ones(2, 2)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [15]:
# Determinante de uma matriz quadrada.
det(matriz)

1.0

In [16]:
# Função que retorna a matriz transposta.
# Tambem pode utilizar o operador ' (Apostrofe).
matriz'
transpose(matriz)

2×2 Transpose{Int64,Array{Int64,2}}:
 1  1
 2  3

In [17]:
# Matriz Inversa.
inv(matriz)

2×2 Array{Float64,2}:
  3.0  -2.0
 -1.0   1.0

In [18]:
# Traço da matriz.
tr(matriz)

4

In [19]:
# Multiplicação de matrizes de acordo com a algebra linear.
matriz * mul

2×2 Array{Int64,2}:
 10  13
 14  18

In [20]:
# Multiplicação elemento a elemento da matriz. A multiplicação é realizada entre as mesmas posições.
matriz .* mul

2×2 Array{Int64,2}:
 2   6
 4  15

In [21]:
# Produto Interno ( ou escalar ) entre vetores ou matrizes.
dot(dados, rel)

290

In [22]:
# Função que calcula o posto de uma matriz.
rank(matriz)

2

In [23]:
# Função que calcula a norma de uma matriz.
norm(dados)

14.142135623730951

In [24]:
# Autovalores de uma matriz.
eigvals(matriz)

2-element Array{Float64,1}:
 0.2679491924311228
 3.732050807568877 

In [25]:
# Autovetores de uma matriz.
eigvecs(matriz)

2×2 Array{Float64,2}:
 -0.939071  -0.59069 
  0.343724  -0.806898

In [26]:
# Fatoração LU de uma matriz.
lu(matriz)

LU{Float64,Array{Float64,2}}
L factor:
2×2 Array{Float64,2}:
 1.0  0.0
 1.0  1.0
U factor:
2×2 Array{Float64,2}:
 1.0  2.0
 0.0  1.0

## Trigonometria Básica
<p>Contém funções básicas de trigonometria que podem ser utilizadas para encontrar direções, e outros, alem de realizar calculos de ângulos.</p>

In [27]:
# Raiz quadrada de um valor ou matriz.
sqrt(25)

5.0

In [28]:
# Eleva a constante e (Euler) a um valor numérico.
exp(1)

2.718281828459045

In [29]:
# Função Seno (Radioanos).
sin(10);
# Função Cosseno (Radianos).
cos(10);
# Função Tangente (Radianos).
tan(10);

In [30]:
# Função Secante (Radianos).
sec(10);
# Função Cossecante (Radianos).
csc(10);
# Função Cotangente (Radianos).
cot(10);